DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS TextData;
DROP TABLE IF EXISTS cfg;
DROP TABLE IF EXISTS BinData;
DROP TABLE IF EXISTS CardData;
CREATE TABLE cfg (id SERIAL PRIMARY KEY, flagRunAddr VARCHAR(100), apiRunAddr VARCHAR(100), flnm VARCHAR(100), tssb VARCHAR(100));
CREATE TABLE users (id SERIAL PRIMARY KEY, lgn VARCHAR(100), psw VARCHAR(100), token VARCHAR(300), delFlag INTEGER DEFAULT 0);
CREATE TABLE TextData (id SERIAL PRIMARY KEY, token VARCHAR(300), txxt VARCHAR(300), delFlag INTEGER DEFAULT 0)
CREATE TABLE BinData (id SERIAL PRIMARY KEY, token VARCHAR(300), bin VARCHAR(300), delFlag INTEGER DEFAULT 0)
CREATE TABLE CardData (id SERIAL PRIMARY KEY, token VARCHAR(300), credNum VARCHAR(16), credHolder VARCHAR(300), credCVV VARCHAR(3), delFlag INTEGER DEFAULT 0)